version: "3"

networks:
  redis-net:
    driver: bridge

services:
  redis:
    image: redis:7.4-alpine
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
    command: ["redis-server"]
    networks:
      - redis-net

  surl:
    depends_on:
      redis:
        condition: service_healthy
    build: .
    ports:
      - "8080:8080"
    networks:
      - redis-net
